services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=datacenter
      - POSTGRES_USER=roja
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  etl:
    build: .
    command:  https://raw.githubusercontent.com/RbKuchipudi9/Homeworks/Lab2/Austin_Animal_Center_Outcomes_20231017.csv
    depends_on:
      - db

volumes: 
  db_data:   



# services:
#   web:
#     build: .
#     ports:
#       - "8000:5000"
#     volumes:
#       - .:/code
#     environment:
#       FLASK_DEBUG: "true"
#   redis:
#     image: "redis:alpine"